/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.salaryapp;

import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter; 
import java.io.FileWriter;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class FrameUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nik_karyawan = new javax.swing.JLabel();
        nama_karyawan = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JLabel();
        tgl_lahir = new javax.swing.JLabel();
        txtField_nik = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txtField_nama = new javax.swing.JTextField();
        rbtn_pria = new javax.swing.JRadioButton();
        rbtn_wanita = new javax.swing.JRadioButton();
        jabatan = new javax.swing.JLabel();
        Cb_jabatan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        spinner_jumlahdata = new javax.swing.JSpinner();
        jmlh_data = new javax.swing.JLabel();
        cb_freelance = new javax.swing.JCheckBox();
        cb_karyawan = new javax.swing.JCheckBox();
        status = new javax.swing.JLabel();
        terbilang = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_terbilang = new javax.swing.JTextArea();
        nama_karyawan1 = new javax.swing.JLabel();
        txtField_nama1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        label_gajipokok = new javax.swing.JLabel();
        label_jabatan = new javax.swing.JLabel();
        txtField_gaji = new javax.swing.JTextField();
        txtField_jabatan = new javax.swing.JTextField();
        label_tunjanganbpjs = new javax.swing.JLabel();
        txtField_bpjs = new javax.swing.JTextField();
        label_lembur = new javax.swing.JLabel();
        txtField_lembur = new javax.swing.JTextField();
        label_pemasukan_lainnya = new javax.swing.JLabel();
        txt_pemasukanLain = new javax.swing.JTextField();
        label_total = new javax.swing.JLabel();
        txt_totalPemasukan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        label_bpjsKesehatan = new javax.swing.JLabel();
        label_bpjKetenagakerjaan = new javax.swing.JLabel();
        label_pajak = new javax.swing.JLabel();
        txt_bpjsKesehatan = new javax.swing.JTextField();
        txt_bpjsKetenagakerjaan = new javax.swing.JTextField();
        txt_pajak = new javax.swing.JTextField();
        label_total2 = new javax.swing.JLabel();
        txt_totalPengurangan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_outputKeterangan = new javax.swing.JTable();
        btn_hitung = new javax.swing.JButton();
        label_gajibersih = new javax.swing.JLabel();
        txt_gajiBersih = new javax.swing.JTextField();

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        nik_karyawan.setText("NIK");

        nama_karyawan.setText("NAMA");

        jenis_kelamin.setText("JENIS KELAMIN");

        tgl_lahir.setText("TGL LAHIR");

        txtField_nik.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtField_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_nikActionPerformed(evt);
            }
        });

        txt_date.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });

        txtField_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtField_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_namaActionPerformed(evt);
            }
        });

        genderGroup.add(rbtn_pria);
        rbtn_pria.setText("PRIA");
        rbtn_pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_priaActionPerformed(evt);
            }
        });

        genderGroup.add(rbtn_wanita);
        rbtn_wanita.setText("WANITA");

        jabatan.setText("JABATAN");

        Cb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff Admin", "Staff Finance", "Staff Teknisi" }));
        Cb_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_jabatanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("SLIP GAJI KARYAWAN");

        jmlh_data.setText("JUMLAH DATA PENGGAJIAN");

        cb_freelance.setText("Freelance");
        cb_freelance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_freelanceActionPerformed(evt);
            }
        });

        cb_karyawan.setText("Karyawan");
        cb_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_karyawanActionPerformed(evt);
            }
        });

        status.setText("STATUS");

        terbilang.setText("Terbilang");

        txtArea_terbilang.setColumns(20);
        txtArea_terbilang.setRows(5);
        jScrollPane2.setViewportView(txtArea_terbilang);

        nama_karyawan1.setText("PERIODE");

        txtField_nama1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtField_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_nama1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nik_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_karyawan))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jmlh_data, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jenis_kelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_karyawan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(txtField_nik))
                                    .addComponent(Cb_jabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_freelance, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(terbilang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtn_pria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtn_wanita))
                    .addComponent(txtField_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(spinner_jumlahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_nama1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nik_karyawan)
                    .addComponent(txtField_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_karyawan)
                    .addComponent(txtField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_lahir)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis_kelamin)
                    .addComponent(rbtn_pria)
                    .addComponent(rbtn_wanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatan)
                    .addComponent(jmlh_data)
                    .addComponent(spinner_jumlahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(terbilang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_karyawan1)
                            .addComponent(status)
                            .addComponent(cb_karyawan)
                            .addComponent(cb_freelance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Pemasukan");

        label_gajipokok.setText("Gaji Pokok");

        label_jabatan.setText("Tunjangan Jabatan");

        txtField_gaji.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtField_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_gajiActionPerformed(evt);
            }
        });

        txtField_jabatan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        label_tunjanganbpjs.setText("Tunjangan BPJS");

        txtField_bpjs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtField_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_bpjsActionPerformed(evt);
            }
        });

        label_lembur.setText("Lembur");

        txtField_lembur.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        label_pemasukan_lainnya.setText("Pemasukan Lainnya");

        txt_pemasukanLain.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pemasukanLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pemasukanLainActionPerformed(evt);
            }
        });

        label_total.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        label_total.setText("TOTAL");

        txt_totalPemasukan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalPemasukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_gajipokok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_jabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(label_tunjanganbpjs, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_lembur, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtField_lembur, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_gaji, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_jabatan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_bpjs, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_totalPemasukan, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_pemasukan_lainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pemasukanLain, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_gajipokok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tunjanganbpjs)
                    .addComponent(txtField_bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lembur)
                    .addComponent(txtField_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pemasukanLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pemasukan_lainnya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_total)
                    .addComponent(txt_totalPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Pengurangan");

        label_bpjsKesehatan.setText("BPJS KESEHATAN");

        label_bpjKetenagakerjaan.setText("BPJS KETENAGAKERJAAN ");

        label_pajak.setText("Pajak");

        txt_bpjsKesehatan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_bpjsKesehatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bpjsKesehatanActionPerformed(evt);
            }
        });

        txt_bpjsKetenagakerjaan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_pajak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pajakActionPerformed(evt);
            }
        });

        label_total2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        label_total2.setText("TOTAL");

        txt_totalPengurangan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalPenguranganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label_total2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_bpjKetenagakerjaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_bpjsKesehatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_pajak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bpjsKesehatan, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txt_bpjsKetenagakerjaan)
                            .addComponent(txt_pajak)
                            .addComponent(txt_totalPengurangan)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_bpjsKesehatan)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_bpjsKesehatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_bpjKetenagakerjaan)
                            .addComponent(txt_bpjsKetenagakerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pajak)
                    .addComponent(txt_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_total2)
                    .addComponent(txt_totalPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        tbl_outputKeterangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Jabatan", "Status", "Total Pemasukan", "Total Pengurangan", "Total Bersih"
            }
        ));
        jScrollPane1.setViewportView(tbl_outputKeterangan);

        btn_hitung.setBackground(new java.awt.Color(255, 255, 255));
        btn_hitung.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        label_gajibersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_gajibersih.setText("Gaji Bersih");

        txt_gajiBersih.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_gajiBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gajiBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hitung))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(label_gajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(txt_gajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hitung)
                    .addComponent(label_gajibersih)
                    .addComponent(txt_gajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_nikActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txtField_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_namaActionPerformed

    private void rbtn_priaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_priaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_priaActionPerformed

    private void Cb_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_jabatanActionPerformed

    private void txtField_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_gajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_gajiActionPerformed

    private void txt_bpjsKesehatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bpjsKesehatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bpjsKesehatanActionPerformed

    private void txt_totalPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalPenguranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalPenguranganActionPerformed

    private void txtField_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_bpjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_bpjsActionPerformed

    private void txt_pemasukanLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pemasukanLainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pemasukanLainActionPerformed

    private void cb_freelanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_freelanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_freelanceActionPerformed

    private void cb_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_karyawanActionPerformed

    private void txt_totalPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalPemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalPemasukanActionPerformed

    private void txt_gajiBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gajiBersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gajiBersihActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        //Kode fungsi dari tombol 
        if(txtField_nik.getText().isEmpty() || txtField_nama.getText(). isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama atau NIK belum lengkap", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else if (rbtn_pria.isSelected()== false 
                && rbtn_wanita.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum terpilih", 
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else if (txt_date.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tanggal lahir belum diisi",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else if (txtField_gaji.getText().isEmpty() 
                || txtField_jabatan.getText().isEmpty() 
                || txtField_bpjs.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Gaji atau Tunjangan belum diisi",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else if (txt_bpjsKesehatan.getText().isEmpty() 
                || txt_bpjsKetenagakerjaan.getText().isEmpty() 
                || txt_pajak.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "BPJS atau Pajak belum diisi",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            //Fungsi dari tombol hitung
            double gaji           = Double.parseDouble(txtField_gaji.getText()),
                   jabatan        = Double.parseDouble(txtField_jabatan.getText()),
                   bpjs           = Double.parseDouble(txtField_bpjs.getText()),
                   pajak          = Double.parseDouble(txt_pajak.getText()),
                   Lainnya        = Double.parseDouble(txt_pemasukanLain.getText()),
                   bpjsKesehatan  = Double.parseDouble(txt_bpjsKesehatan.getText()),
                   bpjsKetenaga   = Double.parseDouble(txt_bpjsKetenagakerjaan.getText()),
                   totalPemasukan, totalPengurangan, gajiBersih;
                   
            if(txtField_lembur.getText().isEmpty()) {
                //Kode jika tidak ada lembur
                totalPemasukan = gaji + jabatan + bpjs + Lainnya;
                txt_totalPemasukan.setText("" + totalPemasukan);
            }else{
                //Kode jika ada lembur
                double lembur         = Double.parseDouble(txtField_lembur.getText());
                totalPemasukan = gaji + jabatan + bpjs + lembur + Lainnya;
                txt_totalPemasukan.setText("" + totalPemasukan);
            }
            totalPengurangan = bpjsKesehatan + bpjsKetenaga + pajak;
            txt_totalPengurangan.setText("" + totalPengurangan);
            
            gajiBersih = totalPemasukan - totalPengurangan;
            txt_gajiBersih.setText("" + gajiBersih);
            
            tbl_outputKeterangan.g("nik_karyawan" + txtField_nik.getText() + "nama_karyawan" 
                    + txtField_nama.getText() + "jabatan" 
                    + Cb_jabatan.getSelectedItem() + "status" + cb_karyawan.getSelectedObjects(), cb_freelance.getSelectedObjects()
                    + "label_total" + totalPemasukan + "label_total2" + totalPengurangan + "label_gajibersih" + gajiBersih);
        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void txt_pajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pajakActionPerformed

    private void txtField_nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_nama1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_jabatan;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JCheckBox cb_freelance;
    private javax.swing.JCheckBox cb_karyawan;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel jenis_kelamin;
    private javax.swing.JLabel jmlh_data;
    private javax.swing.JLabel label_bpjKetenagakerjaan;
    private javax.swing.JLabel label_bpjsKesehatan;
    private javax.swing.JLabel label_gajibersih;
    private javax.swing.JLabel label_gajipokok;
    private javax.swing.JLabel label_jabatan;
    private javax.swing.JLabel label_lembur;
    private javax.swing.JLabel label_pajak;
    private javax.swing.JLabel label_pemasukan_lainnya;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total2;
    private javax.swing.JLabel label_tunjanganbpjs;
    private javax.swing.JLabel nama_karyawan;
    private javax.swing.JLabel nama_karyawan1;
    private javax.swing.JLabel nik_karyawan;
    private javax.swing.JRadioButton rbtn_pria;
    private javax.swing.JRadioButton rbtn_wanita;
    private javax.swing.JSpinner spinner_jumlahdata;
    private javax.swing.JLabel status;
    private javax.swing.JTable tbl_outputKeterangan;
    private javax.swing.JLabel terbilang;
    private javax.swing.JLabel tgl_lahir;
    private javax.swing.JTextArea txtArea_terbilang;
    private javax.swing.JTextField txtField_bpjs;
    private javax.swing.JTextField txtField_gaji;
    private javax.swing.JTextField txtField_jabatan;
    private javax.swing.JTextField txtField_lembur;
    private javax.swing.JTextField txtField_nama;
    private javax.swing.JTextField txtField_nama1;
    private javax.swing.JTextField txtField_nik;
    private javax.swing.JTextField txt_bpjsKesehatan;
    private javax.swing.JTextField txt_bpjsKetenagakerjaan;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_gajiBersih;
    private javax.swing.JTextField txt_pajak;
    private javax.swing.JTextField txt_pemasukanLain;
    private javax.swing.JTextField txt_totalPemasukan;
    private javax.swing.JTextField txt_totalPengurangan;
    // End of variables declaration//GEN-END:variables
}
